//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proy_PI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class requerimientos
    {
        [Key]
        public string codigoProyectoFK { get; set; }
        [Key]
        public string nombreModuloFK { get; set; }
        [Key]
        public string idPK { get; set; }
        public string descripcion { get; set; }
        public int peso { get; set; }
        public string estado { get; set; }
        public string cedulaEmpleadoFK { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> duraciónEstimada { get; set; }
        public Nullable<int> duraciónReal { get; set; }
    
        public virtual modulos modulos { get; set; }
    }
}
