//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conocimientos
    {
        [Key]
        [Display(Name = "Cédula de empleado")]
        public string cedulaEmpleadoFK { get; set; }

        [Key]
        [Display(Name = "Conocimiento")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string conocimientoPK { get; set; }
    
        public virtual empleados empleados { get; set; }

        public List<conocimientos> listaConocimientos { get; set; }

        public conocimientos modeloConocimientos { get; set; }
    }
}
