//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conocimientos
    {
        public string cedulaEmpleadoFK { get; set; }
        public string conocimientoPK { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
