//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.conocimientos = new HashSet<conocimientos>();
            this.roles = new HashSet<roles>();
        }
    
        [Key]
        [Display(Name = "Cédula")]
        public string cedulaPK { get; set; }

        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Display(Name = "Primer Apellido")]
        public string apellido1 { get; set; }

        [Display(Name = "Segundo Apellido")]
        public string apellido2 { get; set; }

        [Display(Name = "Edad")]
        public Nullable<int> edad { get; set; }

        [Display(Name = "Fecha de Nacimiento")]
        public System.DateTime fechaNacimiento { get; set; }

        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }

        [Display(Name = "Correo")]
        public string correo { get; set; }

        [Display(Name = "Dirección Completa")]
        public string direccionDetallada { get; set; }

        [Display(Name = "Disponibilidad")]
        public bool disponibilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conocimientos> conocimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles> roles { get; set; }
    }
}
