//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_mejorado.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.proyectos = new HashSet<proyectos>();
        }

        [Key]
        [StringLength(9)]
        [RegularExpression(@"^[0-9]+", ErrorMessage = "La cédula solo puede estar compuesta por números")]
        [Display(Name = "Cédula")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string cedulaPK { get; set; }

        [StringLength(20)]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "El nombre solo puede estar compuesto por letras")]
        [Display(Name = "Nombre de cliente")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string nombre { get; set; }

        [StringLength(20)]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "Los Apellido solo puede estar compuesto por letras")]
        [Display(Name = "Primer Apellido")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string apellido1 { get; set; }

        [StringLength(20)]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$", ErrorMessage = "Los Apellido solo puede estar compuesto por letras")]
        [Display(Name = "Segundo Apellido")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string apellido2 { get; set; }

        [StringLength(15)]
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "El número de telefono solo úede estar compuesto por números,y no puede iniciar con el numero 0")]
        public string telefono { get; set; }

        [StringLength(20)]
        [Display(Name = "Provincia")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string provincia { get; set; }

        [StringLength(20)]
        [Display(Name = "Cantón")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string canton { get; set; }

        [StringLength(20)]
        [Display(Name = "Distrito")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string distrito { get; set; }

        [StringLength(25)]
        [Display(Name = "E-mail")]
        public string correo { get; set; }

        [Display(Name = "Direccion detallada")]
        public string direccionDetallada { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos> proyectos { get; set; }
    }
}
