//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_mejorado.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class conocimientos
    {
        [Key]
        [Display(Name = "Nombre de empleado")]
        public string cedulaEmpleadoFK { get; set; }

        [Key]
        [Display(Name = "Conocimiento")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string conocimientoPK { get; set; }


        public virtual empleados empleados { get; set; }

        public List<conocimientos> listaConocimientos { get; set; }

        public conocimientos modeloConocimientos { get; set; }
    }
}
