//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_mejorado.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos()
        {
            this.modulos = new HashSet<modulos>();
            this.roles = new HashSet<roles>();
        }

        [Key]
        [Display(Name = "Código del Proyecto")]
        public int codigoPK { get; set; }
        [Display(Name = "Nombre del Proyecto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [RegularExpression(@"^[a-zA-Z0-9,.\s]+$", ErrorMessage = "El objetivo no permite el uso de algunos símbolos")]
        public string nombre { get; set; }
        [Display(Name = "Fecha de inicio")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fechaInicio { get; set; }
        [Display(Name = "Fecha final estimada")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fechaFinalEstimada { get; set; }
        [Display(Name = "Costo estimado")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#}")]
        public decimal costoEstimado { get; set; }
        [Display(Name = "Objetivo del Proyecto")]
        [RegularExpression(@"^[a-zA-Z0-9,.\s]+$", ErrorMessage = "El objetivo no permite el uso de algunos símbolos")]
        public string objetivo { get; set; }
        [Display(Name = "Cédula de cliente")]
        public string cedulaClienteFK { get; set; }
        [Display(Name = "ID de equipo")]
        public Nullable<int> idEquipo { get; set; }
        [Display(Name = "Fecha final")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaFinal { get; set; }
        [Display(Name = "Costo real")]
        public Nullable<decimal> costoReal { get; set; }
        [NotMapped]
        [Display(Name = "Nombre de líder")]
        public string cedulaLider { get; set; }

        public virtual empleados empleados { get; set; }

        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modulos> modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles> roles { get; set; }
    }
}
