//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador_mejorado.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class requerimientos
    {
        [Key]
        public int codigoProyectoFK { get; set; }
        [Key]
        public int idModuloFK { get; set; }
        [Key]
        public int idPK { get; set; }
        public string descripcion { get; set; }
        public int complejidad { get; set; }
        public string estado { get; set; }
        public string cedulaEmpleadoFK { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public System.DateTime duraciónEstimada { get; set; }
        public Nullable<System.DateTime> duraciónReal { get; set; }
        public string nombre { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual modulos modulos { get; set; }
    }
}
